sudo: required

language: node_js

services:
  - docker

node_js:
  - "4.2"

# https://github.com/travis-ci/travis-ci/issues/4778
before_install:
  - sudo service docker restart; sleep 10;

install:
  - npm install
  - npm install -g gulp

script:
  - gulp ci --tag=${TRAVIS_TAG}
